Update user.go
andygrunwald/go-jira pull request #439
Opened 2022-02-16 02:41 UTC by metalbreeze

# Description
According https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-user-search/#api-rest-api-2-user-search-get
add  those username/accountId/property  parameters to this find method

Information that is useful here:
* **The What**: add some paramater method to support find method
* **The Why**: Without this,  _The username query parameter was not provided_ error msg will be return
* **Type of change**:  add missing paramater support 
* **Breaking change**:Backward compatible
* **Related to an issue**: N/A
* **Jira Version + Type**: Jira v8.13.9

## Example:

```go
jiraClient.User.Find("",jira.WithUsername("xxx@xxx.com"))
```

# Checklist

* [ ] Unit or Integration tests added
  * [ ] Good Path
  * [ ] Error Path
* [ ] Commits follow conventions described here:
  * [ ] [Conventional Commits 1.0.0](https://conventionalcommits.org/en/v1.0.0-beta.4/#summary)
  * [x] [The seven rules of a great Git commit message](https://chris.beams.io/posts/git-commit/#seven-rules)
* [ ] Commits are squashed such that
  * [ ] There is 1 commit per isolated change
* [x] I've not made extraneous commits/changes that are unrelated to my change.

2022-02-16 02:49 UTC, metalbreeze commented
Add Username,AccountId,Property support in UserService Find method.

And some func similary with func WithMaxResults.

2022-02-18 15:22 UTC, benjivesterby approved these changes

2022-02-18 15:23 UTC, benjivesterby requested changes
Looks like these are failing linter checks. Please `go fmt` the file and push the changes

2022-02-19 09:35 UTC, metalbreeze commented
done  by go fomat file

2022-02-20 11:26 UTC, metalbreeze commented
fix some compile error by re-compile it .

2022-02-20 13:29 UTC, metalbreeze commented
wow. great. finally.

2022-02-20 15:56 UTC, benjivesterby approved these changes

2022-02-20 15:56 UTC, merged